# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-19 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20190317_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='author',
            field=models.TextField(max_length=100),
        ),
    ]
