# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-19 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20190319_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='thread',
            name='value',
            field=models.TextField(max_length=5000),
        ),
    ]
