# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-01 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20190402_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='author',
            field=models.CharField(default='ayush', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 21, 5, 11, 914707, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='rfile',
            field=models.FileField(default='fefeomfoef', upload_to=''),
            preserve_default=False,
        ),
    ]
