# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-12 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='thread',
            new_name='Thread',
        ),
    ]
