# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-15 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190312_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='subject',
            field=models.CharField(default='ayush', max_length=5000),
            preserve_default=False,
        ),
    ]
