# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-17 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='time',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='ayush', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='author_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='author_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
