# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-17 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20190317_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 17, 14, 38, 12, 957240, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
