# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-24 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20190319_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfile', models.FileField(upload_to='')),
                ('created', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
